CREATE TABLE objection_codes (
    code        VARCHAR(6)    NOT NULL,
    kind        VARCHAR(20)   NOT NULL,
    concept     CHAR(2)       NOT NULL,
    group_code  CHAR(4)       NOT NULL,
    applicable  BOOLEAN       NOT NULL,
    description VARCHAR(400)  NOT NULL,

    CONSTRAINT pk_objection_codes PRIMARY KEY (code),
    CONSTRAINT chk_objection_codes_kind CHECK (kind IN ('DEVOLUTION', 'GLOSS', 'RESPONSE')),
    CONSTRAINT chk_objection_codes_code CHECK (REGEXP_LIKE(code, '^(DE|FA|TA|SO|AU|CO|CL|SA|RE)[0-9]{2}([0-9]{2})?$', 'c')),
    CONSTRAINT chk_objection_codes_group CHECK (group_code = LEFT(code, 4) AND concept = LEFT(code, 2)),
    CONSTRAINT chk_objection_codes_applicable CHECK (applicable = (CHAR_LENGTH(code) = 6))
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO objection_codes (code, kind, concept, group_code, applicable, description) VALUES
    ('DE16', 'DEVOLUTION', 'DE', 'DE16', FALSE, 'Persona corresponde a otro responsable de pago'),
    ('DE1601', 'DEVOLUTION', 'DE', 'DE16', TRUE, 'La factura corresponde a una persona que pertenecía a otro responsable de pago en el momento de la atención'),
    ('DE44', 'DEVOLUTION', 'DE', 'DE44', FALSE, 'El prestador de servicios de salud que factura no hace parte de la red integral e integrada de la entidad responsable de pago'),
    ('DE4401', 'DEVOLUTION', 'DE', 'DE44', TRUE, 'El profesional que ordenó el servicio o tecnología de salud facturado lo hizo desde una IPS que no hace parte de la red integral e integrada de la entidad responsable de pago'),
    ('DE4402', 'DEVOLUTION', 'DE', 'DE44', TRUE, 'El profesional independiente que ordenó el servicio o tecnología de salud no hace parte de la red integral e integrada de la entidad responsable de pago'),
    ('DE50', 'DEVOLUTION', 'DE', 'DE50', FALSE, 'Factura ya pagada o en trámite'),
    ('DE5001', 'DEVOLUTION', 'DE', 'DE50', TRUE, 'La totalidad de la factura fue pagada por la entidad responsable de pago'),
    ('DE5002', 'DEVOLUTION', 'DE', 'DE50', TRUE, 'La factura ya fue radicada a la entidad responsable de pago y se encuentra en trámite'),
    ('DE56', 'DEVOLUTION', 'DE', 'DE56', FALSE, 'No radicación de los soportes dentro de los veintidós (22) días hábiles siguientes a la fecha de expedición de la factura conforme al artículo 5 de la Resolución 510 de 2022 o la que la modifique o sustituya'),
    ('DE5601', 'DEVOLUTION', 'DE', 'DE56', TRUE, 'El prestador de servicios de salud o proveedor de tecnologías en salud no radica los soportes dentro de los veintidós (22) días hábiles siguientes a la fecha de expedición de la factura conforme al artículo 5 de la Resolución 510 de 2022 o la que la modifique o sustituya'),
    ('FA01', 'GLOSS', 'FA', 'FA01', FALSE, 'Estancia u observación de urgencias'),
    ('FA0101', 'GLOSS', 'FA', 'FA01', TRUE, 'El cargo por estancia u observación de urgencias, que viene relacionado o justificado en los soportes de cobro, presenta diferencia con las cantidades facturadas'),
    ('FA0102', 'GLOSS', 'FA', 'FA01', TRUE, 'Se facturan consultas, interconsultas o atenciones (visitas) domiciliarias que están incluidas en la estancia u observación de urgencias de acuerdo con lo pactado'),
    ('FA0103', 'GLOSS', 'FA', 'FA01', TRUE, 'Se cobra estancia u observación de urgencias que ya se encuentra incluida en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA0105', 'GLOSS', 'FA', 'FA01', TRUE, 'Se facturan servicios o tecnologías en salud que se encuentran incluidos en la estancia u observación de urgencias de acuerdo con lo pactado'),
    ('FA02', 'GLOSS', 'FA', 'FA02', FALSE, 'Consultas, interconsultas y atenciones (visita) domiciliaria'),
    ('FA0201', 'GLOSS', 'FA', 'FA02', TRUE, 'El cargo por consulta, interconsulta o atención (visita) domiciliaria que viene relacionado o justificado en los soportes de cobro, presenta diferencias con las cantidades facturadas'),
    ('FA0202', 'GLOSS', 'FA', 'FA02', TRUE, 'Se cobran consultas o atenciones (visitas) domiciliarias que se encuentran incluidas en los honorarios profesionales post quirúrgicos'),
    ('FA0203', 'GLOSS', 'FA', 'FA02', TRUE, 'Se cobran consultas o atenciones (visitas) domiciliarias que ya se encuentran incluidas en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA0205', 'GLOSS', 'FA', 'FA02', TRUE, 'Se cobran consultas que se encuentran incluidas en los honorarios profesionales del procedimiento, de acuerdo con lo pactado por las partes'),
    ('FA0206', 'GLOSS', 'FA', 'FA02', TRUE, 'En una factura se registra una interconsulta que originó la práctica de un procedimiento quirúrgico o intervencionista que realizó el mismo prestador'),
    ('FA03', 'GLOSS', 'FA', 'FA03', FALSE, 'Honorarios profesionales en procedimientos'),
    ('FA0301', 'GLOSS', 'FA', 'FA03', TRUE, 'Los cargos por honorarios profesionales en procedimientos quirúrgicos o intervencionistas, que vienen relacionados o justificados en los soportes de cobro, presentan diferencias con las cantidades que fueron facturadas'),
    ('FA0302', 'GLOSS', 'FA', 'FA03', TRUE, 'Los cargos por honorarios de anestesia que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA0303', 'GLOSS', 'FA', 'FA03', TRUE, 'Se cobran honorarios profesionales que ya se encuentran incluidos en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA05', 'GLOSS', 'FA', 'FA05', FALSE, 'Derechos de sala'),
    ('FA0501', 'GLOSS', 'FA', 'FA05', TRUE, 'Los cargos por derechos de sala que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA0502', 'GLOSS', 'FA', 'FA05', TRUE, 'Se cobran tecnologías en salud que ya se encuentran incluidas en el ítem de derechos de sala o materiales quirúrgicos'),
    ('FA0503', 'GLOSS', 'FA', 'FA05', TRUE, 'Se cobran derechos de sala que ya se encuentran incluidos en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA06', 'GLOSS', 'FA', 'FA06', FALSE, 'Dispositivos médicos'),
    ('FA0601', 'GLOSS', 'FA', 'FA06', TRUE, 'Los cargos por dispositivos médicos que vienen relacionados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA0602', 'GLOSS', 'FA', 'FA06', TRUE, 'Se cobran dispositivos médicos que ya se encuentran incluidos en el ítem de materiales por grupo quirúrgico'),
    ('FA0603', 'GLOSS', 'FA', 'FA06', TRUE, 'Se cobran dispositivos médicos que ya se encuentran incluidos en una atención agrupada'),
    ('FA07', 'GLOSS', 'FA', 'FA07', FALSE, 'Medicamentos y Alimentos para Propósitos Médicos Especiales - APME'),
    ('FA0701', 'GLOSS', 'FA', 'FA07', TRUE, 'Los cargos por medicamentos o APME que vienen relacionados en los soportes de cobro, presentan diferencias con las cantidades que fueron facturadas'),
    ('FA0702', 'GLOSS', 'FA', 'FA07', TRUE, 'Se facturan separadamente principios activos que fueron dispensados en una presentación combinada'),
    ('FA0703', 'GLOSS', 'FA', 'FA07', TRUE, 'Se cobran medicamentos o APME que ya se encuentran incluidos en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA0705', 'GLOSS', 'FA', 'FA07', TRUE, 'Se cobran medicamentos que ya se encuentran incluidos en el procedimiento quirúrgico'),
    ('FA08', 'GLOSS', 'FA', 'FA08', FALSE, 'Apoyo diagnóstico'),
    ('FA0801', 'GLOSS', 'FA', 'FA08', TRUE, 'Los cargos por apoyo diagnóstico que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA0802', 'GLOSS', 'FA', 'FA08', TRUE, 'Se facturan separadamente apoyos diagnósticos incluidos uno en el otro'),
    ('FA0803', 'GLOSS', 'FA', 'FA08', TRUE, 'Se cobran apoyos diagnósticos que ya se encuentran incluidos en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA0805', 'GLOSS', 'FA', 'FA08', TRUE, 'Se cobran apoyos diagnósticos que ya se encuentran incluidos en el procedimiento quirúrgico o intervencionista'),
    ('FA13', 'GLOSS', 'FA', 'FA13', FALSE, 'Factura incluye servicios y tecnologías en salud de diferentes coberturas'),
    ('FA1305', 'GLOSS', 'FA', 'FA13', TRUE, 'Servicio o tecnología corresponde a diferente cobertura'),
    ('FA16', 'GLOSS', 'FA', 'FA16', FALSE, 'Persona, servicio o tecnología pertenecía a otro responsable de pago en el momento de la prestación'),
    ('FA1605', 'GLOSS', 'FA', 'FA16', TRUE, 'En la factura se relacionan una o varias personas que en el momento de la prestación del servicio corresponden a otro responsable de pago'),
    ('FA1606', 'GLOSS', 'FA', 'FA16', TRUE, 'En la factura se relacionan uno o varios servicios o tecnologías en salud que corresponden a otro responsable de pago'),
    ('FA19', 'GLOSS', 'FA', 'FA19', FALSE, 'Error en descuento pactado'),
    ('FA1905', 'GLOSS', 'FA', 'FA19', TRUE, 'Hay descuentos otorgados, que fueron aplicados de manera diferente a lo pactado o no fueron aplicados'),
    ('FA20', 'GLOSS', 'FA', 'FA20', FALSE, 'Pago compartido'),
    ('FA2006', 'GLOSS', 'FA', 'FA20', TRUE, 'Los recaudos efectivos de pagos compartidos o copagos y cuotas moderadoras, que por acuerdo de voluntades efectuó el prestador de servicios de salud o proveedor de tecnologías en salud, no corresponden a lo informado por la entidad responsable de pago para la liquidación del pago compartido'),
    ('FA23', 'GLOSS', 'FA', 'FA23', FALSE, 'Otros procedimientos no quirúrgicos'),
    ('FA2301', 'GLOSS', 'FA', 'FA23', TRUE, 'Los cargos por otros procedimientos no quirúrgicos que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA2302', 'GLOSS', 'FA', 'FA23', TRUE, 'Se facturan separadamente otros procedimientos no quirúrgicos incluidos en otro'),
    ('FA2303', 'GLOSS', 'FA', 'FA23', TRUE, 'Se cobran otros procedimientos no quirúrgicos que ya se encuentran incluidos en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA27', 'GLOSS', 'FA', 'FA27', FALSE, 'Servicio o tecnología de salud ya facturado'),
    ('FA2702', 'GLOSS', 'FA', 'FA27', TRUE, 'Se cobran servicios y tecnologías en salud que se encuentran ya cobrados dentro de la misma u otra factura'),
    ('FA28', 'GLOSS', 'FA', 'FA28', FALSE, 'Servicio o tecnología de salud ya pagada al prestador de servicios de salud o proveedor de tecnologías en salud'),
    ('FA2805', 'GLOSS', 'FA', 'FA28', TRUE, 'Se factura un servicio o tecnología de salud ya pagada por la entidad responsable de pago'),
    ('FA38', 'GLOSS', 'FA', 'FA38', FALSE, 'Traslado asistencial de pacientes'),
    ('FA3801', 'GLOSS', 'FA', 'FA38', TRUE, 'Los cargos por traslado asistencial de pacientes que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA3803', 'GLOSS', 'FA', 'FA38', TRUE, 'Se cobra traslado asistencial de pacientes que ya se encuentran incluidos en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA51', 'GLOSS', 'FA', 'FA51', FALSE, 'Servicio o tecnología prestado o suministrada por un prestador de servicios de salud o proveedor de tecnologías en salud diferente al que tiene a su cargo la atención agrupada'),
    ('FA5103', 'GLOSS', 'FA', 'FA51', TRUE, 'Servicio o tecnología de salud incluido en una atención agrupada, prestado por otro prestador de servicios de salud en caso de urgencias o por proceso de referencia'),
    ('FA5105', 'GLOSS', 'FA', 'FA51', TRUE, 'Servicio o tecnología de salud incluido en una atención agrupada, que hace parte de la RIAS para la promoción y mantenimiento de la salud o la RIAS para la población materno perinatal o aquellas que el Ministerio de Salud y Protección Social disponga como obligatorias, fue prestado o provisto por otro prestador de servicios de salud o proveedor de tecnologías en salud'),
    ('FA5106', 'GLOSS', 'FA', 'FA51', TRUE, 'Servicio o tecnología de salud incluido en una atención agrupada prestado por otro prestador de servicios de salud, con la finalidad de determinar el nivel de control o la aparición de complicaciones de una condición en salud ya establecida'),
    ('FA52', 'GLOSS', 'FA', 'FA52', FALSE, 'Disminución en el número de personas incluidas en una modalidad de pago prospectiva'),
    ('FA5205', 'GLOSS', 'FA', 'FA52', TRUE, 'El número de personas incluidas en la modalidad de pago prospectiva es disminuido por novedades en la base de datos proporcionada por la entidad responsable de pago'),
    ('FA5206', 'GLOSS', 'FA', 'FA52', TRUE, 'La persona incluida en una modalidad de pago prospectiva fallece y aplica una deducción proporcional del valor facturado'),
    ('FA57', 'GLOSS', 'FA', 'FA57', FALSE, 'Apoyo terapéutico'),
    ('FA5701', 'GLOSS', 'FA', 'FA57', TRUE, 'Los cargos por apoyo terapéutico que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA5702', 'GLOSS', 'FA', 'FA57', TRUE, 'Se facturan separadamente apoyos terapéuticos incluidos en otro'),
    ('FA5703', 'GLOSS', 'FA', 'FA57', TRUE, 'Se cobran apoyos terapéuticos que ya se encuentran incluidos en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('FA58', 'GLOSS', 'FA', 'FA58', FALSE, 'Procedimientos quirúrgicos e intervencionistas'),
    ('FA5801', 'GLOSS', 'FA', 'FA58', TRUE, 'Los cargos por procedimientos quirúrgicos o intervencionistas que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA5802', 'GLOSS', 'FA', 'FA58', TRUE, 'Se facturan separadamente procedimientos quirúrgicos o intervencionistas incluidos en otro'),
    ('FA5803', 'GLOSS', 'FA', 'FA58', TRUE, 'Se cobran procedimientos quirúrgicos o intervencionistas que ya se encuentran incluidos en una atención agrupada'),
    ('FA59', 'GLOSS', 'FA', 'FA59', FALSE, 'Transporte no asistencial ambulatorio de la persona'),
    ('FA5901', 'GLOSS', 'FA', 'FA59', TRUE, 'Los cargos por transporte no asistencial ambulatorio de la persona que vienen relacionados o justificados en los soportes de cobro presentan diferencias con las cantidades que fueron facturadas'),
    ('FA5903', 'GLOSS', 'FA', 'FA59', TRUE, 'Se cobra transporte no asistencial ambulatorio de la persona que ya se encuentra incluido en una atención agrupada, de acuerdo con lo pactado por las partes'),
    ('TA01', 'GLOSS', 'TA', 'TA01', FALSE, 'Estancia u observación de urgencias'),
    ('TA0101', 'GLOSS', 'TA', 'TA01', TRUE, 'El cargo por estancias u observación de urgencias, que viene relacionado o justificado en los soportes de cobro, presenta diferencia con los valores pactados o establecidos por la norma'),
    ('TA02', 'GLOSS', 'TA', 'TA02', FALSE, 'Consultas, interconsultas y atenciones (visitas) domiciliarias'),
    ('TA0201', 'GLOSS', 'TA', 'TA02', TRUE, 'El cargo por consulta, interconsulta o atención (visita) domiciliaria que viene relacionado o justificado en los soportes de cobro, presenta diferencias con los valores pactados o establecidos por la norma'),
    ('TA03', 'GLOSS', 'TA', 'TA03', FALSE, 'Honorarios profesionales en procedimientos'),
    ('TA0301', 'GLOSS', 'TA', 'TA03', TRUE, 'Los cargos por honorarios profesionales en procedimientos quirúrgicos o intervencionistas, que vienen relacionados o justificados en los soportes de cobro, presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA0302', 'GLOSS', 'TA', 'TA03', TRUE, 'Los cargos por honorarios de anestesia que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA04', 'GLOSS', 'TA', 'TA04', FALSE, 'Honorarios otro talento humano que interviene en la atención'),
    ('TA0401', 'GLOSS', 'TA', 'TA04', TRUE, 'Los cargos por honorarios de otro talento humano que interviene en la atención que vienen relacionados o justificados en soportes de cobro, presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA05', 'GLOSS', 'TA', 'TA05', FALSE, 'Derechos de sala'),
    ('TA0501', 'GLOSS', 'TA', 'TA05', TRUE, 'Los cargos por derechos de sala que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA06', 'GLOSS', 'TA', 'TA06', FALSE, 'Dispositivos médicos'),
    ('TA0601', 'GLOSS', 'TA', 'TA06', TRUE, 'Los cargos por dispositivos médicos que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA07', 'GLOSS', 'TA', 'TA07', FALSE, 'Medicamentos y Alimentos para Propósitos Médicos Especiales - APME'),
    ('TA0701', 'GLOSS', 'TA', 'TA07', TRUE, 'Los cargos por medicamentos o APME que vienen relacionados o justificados en los soportes de cobro, presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA08', 'GLOSS', 'TA', 'TA08', FALSE, 'Apoyo diagnóstico'),
    ('TA0801', 'GLOSS', 'TA', 'TA08', TRUE, 'Los cargos por apoyo diagnóstico que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA09', 'GLOSS', 'TA', 'TA09', FALSE, 'Atención agrupada'),
    ('TA0901', 'GLOSS', 'TA', 'TA09', TRUE, 'Los cargos por atención agrupada que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados'),
    ('TA23', 'GLOSS', 'TA', 'TA23', FALSE, 'Otros procedimientos no quirúrgicos'),
    ('TA2301', 'GLOSS', 'TA', 'TA23', TRUE, 'Los cargos por otros procedimientos no quirúrgicos que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA29', 'GLOSS', 'TA', 'TA29', FALSE, 'Recargos no pactados'),
    ('TA2901', 'GLOSS', 'TA', 'TA29', TRUE, 'En la factura se adicionan cobros de recargos no pactados previamente entre las partes o establecidos por la norma'),
    ('TA38', 'GLOSS', 'TA', 'TA38', FALSE, 'Traslado asistencial de pacientes'),
    ('TA3801', 'GLOSS', 'TA', 'TA38', TRUE, 'Los cargos por traslado asistencial de pacientes que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA57', 'GLOSS', 'TA', 'TA57', FALSE, 'Apoyo terapéutico'),
    ('TA5701', 'GLOSS', 'TA', 'TA57', TRUE, 'Los cargos por apoyo terapéutico que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA58', 'GLOSS', 'TA', 'TA58', FALSE, 'Procedimientos quirúrgicos e intervencionistas'),
    ('TA5801', 'GLOSS', 'TA', 'TA58', TRUE, 'Los cargos por procedimientos quirúrgicos o intervencionistas que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('TA59', 'GLOSS', 'TA', 'TA59', FALSE, 'Transporte no asistencial ambulatorio de las personas'),
    ('TA5901', 'GLOSS', 'TA', 'TA59', TRUE, 'Los cargos por otro transporte no asistencial ambulatorio de personas que vienen relacionados o justificados en los soportes de cobro presentan diferencias con los valores pactados o establecidos por la norma'),
    ('SO01', 'GLOSS', 'SO', 'SO01', FALSE, 'Estancia u observación de urgencias'),
    ('SO0101', 'GLOSS', 'SO', 'SO01', TRUE, 'Existe ausencia total, parcial o inconsistencia en la epicrisis que soporta la estancia u observación de urgencias'),
    ('SO0102', 'GLOSS', 'SO', 'SO01', TRUE, 'Los soportes de cobro que evidencian la estancia u observación de urgencias no corresponden a la persona atendida'),
    ('SO02', 'GLOSS', 'SO', 'SO02', FALSE, 'Consultas, interconsultas y atenciones (visitas) domiciliarias'),
    ('SO0201', 'GLOSS', 'SO', 'SO02', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian la realización de la consulta, interconsulta o atención (visita) domiciliaria'),
    ('SO0202', 'GLOSS', 'SO', 'SO02', TRUE, 'Los soportes de cobro que evidencian la realización de la consulta, interconsulta o atención (visita) domiciliaria no corresponden a la persona atendida'),
    ('SO03', 'GLOSS', 'SO', 'SO03', FALSE, 'Honorarios profesionales en procedimientos'),
    ('SO0301', 'GLOSS', 'SO', 'SO03', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian los honorarios profesionales en procedimientos quirúrgicos o intervencionistas'),
    ('SO0302', 'GLOSS', 'SO', 'SO03', TRUE, 'Los soportes de cobro que evidencian los honorarios de profesionales en procedimientos no corresponden a la persona atendida'),
    ('SO0303', 'GLOSS', 'SO', 'SO03', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian los honorarios de anestesia'),
    ('SO04', 'GLOSS', 'SO', 'SO04', FALSE, 'Honorarios otro talento humano que interviene en la atención'),
    ('SO0401', 'GLOSS', 'SO', 'SO04', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian los honorarios del talento humano que interviene en la atención, diferente a los quirúrgicos y clínicos'),
    ('SO0402', 'GLOSS', 'SO', 'SO04', TRUE, 'Los soportes de cobro que evidencian los honorarios de otros profesionales asistenciales no corresponden a la persona atendida'),
    ('SO06', 'GLOSS', 'SO', 'SO06', FALSE, 'Dispositivos médicos'),
    ('SO0601', 'GLOSS', 'SO', 'SO06', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian los dispositivos médicos empleados en procedimientos quirúrgicos o intervencionistas que sean motivo de cobro adicional'),
    ('SO0602', 'GLOSS', 'SO', 'SO06', TRUE, 'Los soportes de cobro que evidencian los dispositivos médicos empleados no corresponden a la persona atendida'),
    ('SO0603', 'GLOSS', 'SO', 'SO06', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian los dispositivos médicos empleados en procedimientos no quirúrgicos que sean motivo de cobro adicional'),
    ('SO0604', 'GLOSS', 'SO', 'SO06', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian los dispositivos médicos entregados como parte de una acción de protección específica o tratamiento'),
    ('SO07', 'GLOSS', 'SO', 'SO07', FALSE, 'Medicamentos y Alimentos para Propósitos Médicos Especiales - APME'),
    ('SO0701', 'GLOSS', 'SO', 'SO07', TRUE, 'Existe ausencia total, parcial o inconsistencia en la hoja de administración de medicamentos'),
    ('SO0702', 'GLOSS', 'SO', 'SO07', TRUE, 'Los soportes de cobro que evidencian los medicamentos suministrados no corresponden a la persona atendida'),
    ('SO0703', 'GLOSS', 'SO', 'SO07', TRUE, 'Existe ausencia total, parcial o inconsistencia en el comprobante de recibido de medicamentos de las personas'),
    ('SO08', 'GLOSS', 'SO', 'SO08', FALSE, 'Apoyo diagnóstico'),
    ('SO0801', 'GLOSS', 'SO', 'SO08', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian la práctica del apoyo diagnóstico'),
    ('SO0802', 'GLOSS', 'SO', 'SO08', TRUE, 'Los soportes de cobro que evidencian el apoyo diagnóstico no corresponden a la persona atendida'),
    ('SO0803', 'GLOSS', 'SO', 'SO08', TRUE, 'Existe ausencia en los soportes de cobro de la lectura o interpretación del apoyo diagnóstico por parte del profesional correspondiente'),
    ('SO21', 'GLOSS', 'SO', 'SO21', FALSE, 'Número de autorización'),
    ('SO2101', 'GLOSS', 'SO', 'SO21', TRUE, 'El número de la autorización no está incluido en el RIPS'),
    ('SO2102', 'GLOSS', 'SO', 'SO21', TRUE, 'El número de la autorización incluido en el RIPS no corresponde al prestador de servicios de salud'),
    ('SO2103', 'GLOSS', 'SO', 'SO21', TRUE, 'El número de la autorización de servicios y tecnologías en salud incluido en el RIPS no corresponde al servicio o tecnología prestada o facturada'),
    ('SO2104', 'GLOSS', 'SO', 'SO21', TRUE, 'El número de la autorización incluido en el RIPS no corresponde a la persona atendida'),
    ('SO23', 'GLOSS', 'SO', 'SO23', FALSE, 'Otros procedimientos no quirúrgicos'),
    ('SO2301', 'GLOSS', 'SO', 'SO23', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian la práctica de otros procedimientos no quirúrgicos'),
    ('SO2302', 'GLOSS', 'SO', 'SO23', TRUE, 'Los soportes de cobro que evidencian otros procedimientos no quirúrgicos no corresponden a la persona atendida'),
    ('SO34', 'GLOSS', 'SO', 'SO34', FALSE, 'Resumen de atención o epicrisis, hoja de atención de urgencias u hoja de atención odontológica'),
    ('SO3401', 'GLOSS', 'SO', 'SO34', TRUE, 'Existe ausencia total, parcial o inconsistencia en la epicrisis'),
    ('SO3402', 'GLOSS', 'SO', 'SO34', TRUE, 'La epicrisis no corresponde a la persona atendida'),
    ('SO3403', 'GLOSS', 'SO', 'SO34', TRUE, 'Existe ausencia total, parcial o inconsistencia en la hoja de atención de urgencias'),
    ('SO3404', 'GLOSS', 'SO', 'SO34', TRUE, 'La hoja de atención de urgencias no corresponde a la persona atendida'),
    ('SO3405', 'GLOSS', 'SO', 'SO34', TRUE, 'Existe ausencia total, parcial o inconsistencia en el resumen de atención'),
    ('SO3406', 'GLOSS', 'SO', 'SO34', TRUE, 'El resumen de atención no corresponde a la persona atendida'),
    ('SO3407', 'GLOSS', 'SO', 'SO34', TRUE, 'Existe ausencia total, parcial o inconsistencia en la hoja de atención odontológica'),
    ('SO3408', 'GLOSS', 'SO', 'SO34', TRUE, 'La hoja de atención odontológica no corresponde a la persona atendida'),
    ('SO36', 'GLOSS', 'SO', 'SO36', FALSE, 'Copia de la factura expedida a la aseguradora del SOAT, la ADRES o la entidad que haga sus veces'),
    ('SO3601', 'GLOSS', 'SO', 'SO36', TRUE, 'Existe ausencia total, parcial o inconsistencia en las copias de la factura enviada a la compañía de seguros SOAT, la ADRES o la entidad que haga sus veces, cuando aplica, con sus respectivos detalles, con las que se cumple los topes de cobertura'),
    ('SO3602', 'GLOSS', 'SO', 'SO36', TRUE, 'Las copias de la factura enviada a la compañía de seguros SOAT, la ADRES o la entidad que haga sus veces, cuando aplica, no corresponde a la persona atendida'),
    ('SO37', 'GLOSS', 'SO', 'SO37', FALSE, 'Orden o prescripción facultativa del profesional tratante'),
    ('SO3701', 'GLOSS', 'SO', 'SO37', TRUE, 'Existe ausencia total, parcial o inconsistencia en la orden o prescripción facultativa del profesional tratante'),
    ('SO3702', 'GLOSS', 'SO', 'SO37', TRUE, 'La orden o prescripción facultativa no corresponde a la persona atendida'),
    ('SO38', 'GLOSS', 'SO', 'SO38', FALSE, 'Traslado asistencial de pacientes'),
    ('SO3801', 'GLOSS', 'SO', 'SO38', TRUE, 'Existe ausencia total, parcial o inconsistencia en la hoja de traslado asistencial'),
    ('SO3802', 'GLOSS', 'SO', 'SO38', TRUE, 'La hoja de traslado asistencial no corresponde a la persona atendida'),
    ('SO39', 'GLOSS', 'SO', 'SO39', FALSE, 'Comprobante de recibido del usuario'),
    ('SO3901', 'GLOSS', 'SO', 'SO39', TRUE, 'Existe ausencia total, parcial o inconsistencia en el comprobante de recibido del usuario'),
    ('SO3902', 'GLOSS', 'SO', 'SO39', TRUE, 'El comprobante de recibido del usuario no corresponde a la persona atendida'),
    ('SO40', 'GLOSS', 'SO', 'SO40', FALSE, 'Registro de anestesia'),
    ('SO4001', 'GLOSS', 'SO', 'SO40', TRUE, 'Existe ausencia total, parcial o inconsistencia de la copia del registro de anestesia'),
    ('SO4002', 'GLOSS', 'SO', 'SO40', TRUE, 'El registro de anestesia no corresponde a la persona atendida'),
    ('SO41', 'GLOSS', 'SO', 'SO41', FALSE, 'Descripción quirúrgica'),
    ('SO4101', 'GLOSS', 'SO', 'SO41', TRUE, 'Existe ausencia total, parcial o inconsistencia de la copia de la descripción quirúrgica'),
    ('SO4102', 'GLOSS', 'SO', 'SO41', TRUE, 'La descripción quirúrgica no corresponde a la persona atendida'),
    ('SO42', 'GLOSS', 'SO', 'SO42', FALSE, 'Lista de precios'),
    ('SO4201', 'GLOSS', 'SO', 'SO42', TRUE, 'Existe ausencia total, parcial o inconsistencia de la lista de precios'),
    ('SO47', 'GLOSS', 'SO', 'SO47', FALSE, 'Faltan soportes de los servicios y tecnologías en salud de los recobros a cargo de la ADRES o de la ARL'),
    ('SO4701', 'GLOSS', 'SO', 'SO47', TRUE, 'No se incluye en la factura de venta en salud los soportes de los servicios y tecnologías en salud para recobros a cargo de la ADRES, accidentes de trabajo o enfermedad profesional a cargo de la ARL, de conformidad con la normativa vigente'),
    ('SO48', 'GLOSS', 'SO', 'SO48', FALSE, 'Evidencia del envío del trámite respectivo'),
    ('SO4801', 'GLOSS', 'SO', 'SO48', TRUE, 'Existe ausencia total, parcial o inconsistencia en la evidencia del envío del trámite respectivo'),
    ('SO4802', 'GLOSS', 'SO', 'SO48', TRUE, 'El informe de atención de urgencias no corresponde a la persona atendida'),
    ('SO57', 'GLOSS', 'SO', 'SO57', FALSE, 'Apoyo terapéutico'),
    ('SO5701', 'GLOSS', 'SO', 'SO57', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian la práctica del apoyo terapéutico'),
    ('SO5702', 'GLOSS', 'SO', 'SO57', TRUE, 'Los soportes de cobro que evidencian el apoyo terapéutico no corresponden a la persona atendida'),
    ('SO58', 'GLOSS', 'SO', 'SO58', FALSE, 'Procedimientos quirúrgicos e intervencionistas'),
    ('SO5801', 'GLOSS', 'SO', 'SO58', TRUE, 'Existe ausencia total, parcial o inconsistencia en los soportes de cobro que evidencian los procedimientos quirúrgicos o intervencionistas'),
    ('SO5802', 'GLOSS', 'SO', 'SO58', TRUE, 'Los soportes de cobro que evidencian los procedimientos quirúrgicos o intervencionistas no corresponden a la persona atendida'),
    ('SO59', 'GLOSS', 'SO', 'SO59', FALSE, 'Transporte no asistencial ambulatorio de las personas'),
    ('SO5901', 'GLOSS', 'SO', 'SO59', TRUE, 'Existe ausencia total, parcial o inconsistencia en el soporte del transporte no asistencial ambulatorio de la persona'),
    ('SO5902', 'GLOSS', 'SO', 'SO59', TRUE, 'El tiquete de transporte no corresponde a la persona atendida'),
    ('SO61', 'GLOSS', 'SO', 'SO61', FALSE, 'Registro Individual de Prestaciones de Servicios de Salud'),
    ('SO6101', 'GLOSS', 'SO', 'SO61', TRUE, 'En el caso de que uno o varios campos de RIPS presente inconsistencias con la atención prestada'),
    ('SO6102', 'GLOSS', 'SO', 'SO61', TRUE, 'En el caso de que uno o varios campos de RIPS presente inconsistencias con relación al contrato'),
    ('AU01', 'GLOSS', 'AU', 'AU01', FALSE, 'Estancia'),
    ('AU0101', 'GLOSS', 'AU', 'AU01', TRUE, 'El número de días en habitación que vienen relacionados en la factura de venta en salud presenta diferencia con los días autorizados'),
    ('AU0102', 'GLOSS', 'AU', 'AU01', TRUE, 'El servicio de internación donde se produjo la estancia no corresponde al autorizado'),
    ('AU02', 'GLOSS', 'AU', 'AU02', FALSE, 'Consultas, interconsultas y atenciones (visitas) domiciliarias'),
    ('AU0201', 'GLOSS', 'AU', 'AU02', TRUE, 'El número de consultas, interconsultas o atenciones (visitas) domiciliarias que vienen relacionadas en la factura de venta en salud presenta diferencia con las autorizadas'),
    ('AU0202', 'GLOSS', 'AU', 'AU02', TRUE, 'La consulta, interconsulta o atención (visita) domiciliaria relacionada o justificada en los soportes de la factura de venta en salud no corresponde a la autorizada'),
    ('AU03', 'GLOSS', 'AU', 'AU03', FALSE, 'Honorarios profesionales en procedimientos'),
    ('AU0302', 'GLOSS', 'AU', 'AU03', TRUE, 'Los honorarios profesionales relacionados o justificados en los soportes de la factura de venta en salud no corresponden a los autorizados'),
    ('AU0303', 'GLOSS', 'AU', 'AU03', TRUE, 'La entidad responsable de pago emitió autorización directamente al profesional para la ejecución del procedimiento y la IPS está facturando a su nombre estos honorarios'),
    ('AU06', 'GLOSS', 'AU', 'AU06', FALSE, 'Dispositivos médicos'),
    ('AU0601', 'GLOSS', 'AU', 'AU06', TRUE, 'El número de dispositivos médicos que vienen relacionados en la factura de venta en salud presenta diferencia con lo autorizado, sin la debida justificación'),
    ('AU0602', 'GLOSS', 'AU', 'AU06', TRUE, 'Los dispositivos médicos que vienen relacionados o justificados en los soportes de la factura de venta en salud no corresponden a los autorizados, sin la debida justificación'),
    ('AU07', 'GLOSS', 'AU', 'AU07', FALSE, 'Medicamentos y Alimentos para Propósitos Médicos Especiales - APME'),
    ('AU0701', 'GLOSS', 'AU', 'AU07', TRUE, 'El número de unidades de la forma farmacéutica que vienen relacionados en la factura de venta en salud presenta diferencia con lo autorizado'),
    ('AU0702', 'GLOSS', 'AU', 'AU07', TRUE, 'La forma farmacéutica que viene relacionada en la factura de venta en salud presenta diferencia con la autorizada'),
    ('AU0703', 'GLOSS', 'AU', 'AU07', TRUE, 'El principio activo que viene relacionado en la factura de venta en salud presenta diferencia con el autorizado'),
    ('AU0704', 'GLOSS', 'AU', 'AU07', TRUE, 'La concentración que viene relacionada en la factura de venta en salud presenta diferencia con la autorizada'),
    ('AU08', 'GLOSS', 'AU', 'AU08', FALSE, 'Apoyo diagnóstico'),
    ('AU0801', 'GLOSS', 'AU', 'AU08', TRUE, 'El número de apoyos diagnósticos que vienen relacionados en la factura de venta en salud presenta diferencia con lo autorizado'),
    ('AU0802', 'GLOSS', 'AU', 'AU08', TRUE, 'Los apoyos diagnósticos relacionados o justificados en los soportes de la factura de venta en salud no corresponden con los autorizados'),
    ('AU21', 'GLOSS', 'AU', 'AU21', FALSE, 'Número de autorización'),
    ('AU2103', 'GLOSS', 'AU', 'AU21', TRUE, 'El número de la autorización registrado en la factura de venta en salud o RIPS no corresponde al servicio o tecnología prestada o facturada'),
    ('AU23', 'GLOSS', 'AU', 'AU23', FALSE, 'Otros procedimientos no quirúrgicos'),
    ('AU2301', 'GLOSS', 'AU', 'AU23', TRUE, 'El número de procedimientos no quirúrgicos que vienen relacionados en la factura de venta en salud presenta diferencia con lo autorizado'),
    ('AU2302', 'GLOSS', 'AU', 'AU23', TRUE, 'El procedimiento no quirúrgico relacionado o justificado en los soportes de la factura de venta en salud no corresponde con el autorizado'),
    ('AU38', 'GLOSS', 'AU', 'AU38', FALSE, 'Traslado asistencial de pacientes'),
    ('AU3803', 'GLOSS', 'AU', 'AU38', TRUE, 'El traslado asistencial de pacientes no cuenta con la autorización'),
    ('AU43', 'GLOSS', 'AU', 'AU43', FALSE, 'Orden o prescripción facultativa del profesional tratante o autorización de servicios vencida al momento de su dispensación'),
    ('AU4303', 'GLOSS', 'AU', 'AU43', TRUE, 'La orden o prescripción facultativa del profesional tratante o el número de la autorización de servicios registrado en los soportes de cobro ha superado el límite de días de vigencia'),
    ('AU4304', 'GLOSS', 'AU', 'AU43', TRUE, 'La orden o prescripción facultativa del profesional tratante o el número de la autorización de servicios registrado en los soportes de cobro no corresponde a la autorización, orden o prescripción facultativa reemplazada por vencimiento'),
    ('AU57', 'GLOSS', 'AU', 'AU57', FALSE, 'Apoyo terapéutico'),
    ('AU5701', 'GLOSS', 'AU', 'AU57', TRUE, 'El número de apoyos terapéuticos que vienen relacionados en la factura de venta en salud presenta diferencia con lo autorizado'),
    ('AU5702', 'GLOSS', 'AU', 'AU57', TRUE, 'Los apoyos terapéuticos relacionados o justificados en los soportes de la factura de venta en salud no corresponden con los autorizados'),
    ('AU58', 'GLOSS', 'AU', 'AU58', FALSE, 'Procedimientos quirúrgicos e intervencionistas'),
    ('AU5801', 'GLOSS', 'AU', 'AU58', TRUE, 'El número de procedimientos quirúrgicos o intervencionistas que vienen relacionados en la factura de venta en salud presenta diferencia con lo autorizado'),
    ('AU5802', 'GLOSS', 'AU', 'AU58', TRUE, 'Los procedimientos quirúrgicos o intervencionistas que vienen relacionados o justificados en los soportes de la factura de venta en salud no corresponden a los autorizados'),
    ('AU59', 'GLOSS', 'AU', 'AU59', FALSE, 'Transporte no asistencial ambulatorio de las personas'),
    ('AU5903', 'GLOSS', 'AU', 'AU59', TRUE, 'El transporte no asistencial ambulatorio de la persona no cuenta con la autorización'),
    ('CO01', 'GLOSS', 'CO', 'CO01', FALSE, 'Estancia u observación de urgencias'),
    ('CO0101', 'GLOSS', 'CO', 'CO01', TRUE, 'El número de días en observación o habitación que vienen relacionados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO02', 'GLOSS', 'CO', 'CO02', FALSE, 'Consultas, interconsultas y atenciones (visitas) domiciliarias'),
    ('CO0201', 'GLOSS', 'CO', 'CO02', TRUE, 'La consulta, interconsulta o atención (visita) domiciliaria relacionada en los soportes de cobro no está incluida en la respectiva cobertura'),
    ('CO03', 'GLOSS', 'CO', 'CO03', FALSE, 'Honorarios profesionales en procedimientos'),
    ('CO0301', 'GLOSS', 'CO', 'CO03', TRUE, 'Los honorarios profesionales relacionados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO04', 'GLOSS', 'CO', 'CO04', FALSE, 'Honorarios otro talento humano que interviene en la atención'),
    ('CO0401', 'GLOSS', 'CO', 'CO04', TRUE, 'Los honorarios de otros profesionales asistenciales relacionados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO06', 'GLOSS', 'CO', 'CO06', FALSE, 'Dispositivos médicos'),
    ('CO0601', 'GLOSS', 'CO', 'CO06', TRUE, 'Los dispositivos médicos que vienen relacionados o justificados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO07', 'GLOSS', 'CO', 'CO07', FALSE, 'Medicamentos y Alimentos para Propósitos Médicos Especiales - APME'),
    ('CO0701', 'GLOSS', 'CO', 'CO07', TRUE, 'Los medicamentos o APME relacionados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO08', 'GLOSS', 'CO', 'CO08', FALSE, 'Apoyo diagnóstico'),
    ('CO0801', 'GLOSS', 'CO', 'CO08', TRUE, 'Los apoyos diagnósticos relacionados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO23', 'GLOSS', 'CO', 'CO23', FALSE, 'Otros procedimientos no quirúrgicos'),
    ('CO2301', 'GLOSS', 'CO', 'CO23', TRUE, 'Los procedimientos no quirúrgicos relacionados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO38', 'GLOSS', 'CO', 'CO38', FALSE, 'Traslado asistencial de pacientes'),
    ('CO3801', 'GLOSS', 'CO', 'CO38', TRUE, 'El traslado asistencial de pacientes relacionado en los soportes de cobro no está incluido en la respectiva cobertura'),
    ('CO46', 'GLOSS', 'CO', 'CO46', FALSE, 'Cobertura sin agotar en la póliza del seguro obligatorio de accidentes de tránsito SOAT, la ADRES o la entidad que haga sus veces'),
    ('CO4601', 'GLOSS', 'CO', 'CO46', TRUE, 'Se facturan servicios a la entidad responsable de pago sin agotar los topes cubiertos por la póliza de Seguro Obligatorio de Accidentes de Tránsito (SOAT), la ADRES o la entidad que haga sus veces'),
    ('CO57', 'GLOSS', 'CO', 'CO57', FALSE, 'Apoyo terapéutico'),
    ('CO5701', 'GLOSS', 'CO', 'CO57', TRUE, 'Los apoyos terapéuticos relacionados en los soportes de cobro no están incluidos en la respectiva cobertura o hacen parte integral de un servicio y se están cobrando adicionalmente'),
    ('CO58', 'GLOSS', 'CO', 'CO58', FALSE, 'Procedimientos quirúrgicos e intervencionistas'),
    ('CO5801', 'GLOSS', 'CO', 'CO58', TRUE, 'Los procedimientos quirúrgicos o intervencionistas relacionados en los soportes de cobro no están incluidos en la respectiva cobertura'),
    ('CO59', 'GLOSS', 'CO', 'CO59', FALSE, 'Transporte no asistencial ambulatorio de las personas'),
    ('CO5901', 'GLOSS', 'CO', 'CO59', TRUE, 'El transporte no asistencial ambulatorio de la persona relacionado en los soportes de cobro no está incluido en la respectiva cobertura o hacen parte integral de un servicio y se están cobrando adicionalmente'),
    ('CL01', 'GLOSS', 'CL', 'CL01', FALSE, 'Estancia u observación de urgencias'),
    ('CL0101', 'GLOSS', 'CL', 'CL01', TRUE, 'El cargo por estancia sea en observación de urgencias o habitación, que viene relacionado en los soportes de la factura de venta en salud no es pertinente'),
    ('CL02', 'GLOSS', 'CL', 'CL02', FALSE, 'Consultas, interconsultas y atenciones (visitas) domiciliarias'),
    ('CL0201', 'GLOSS', 'CL', 'CL02', TRUE, 'El cargo por consulta, interconsulta o atención (visita) domiciliaria que viene relacionado en los soportes de cobro no es pertinente'),
    ('CL03', 'GLOSS', 'CL', 'CL03', FALSE, 'Honorarios profesionales en procedimientos'),
    ('CL0301', 'GLOSS', 'CL', 'CL03', TRUE, 'Los cargos por honorarios profesionales en procedimientos quirúrgicos o intervencionistas, de hemodinamia, radiología u otros procedimientos que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL0302', 'GLOSS', 'CL', 'CL03', TRUE, 'Los cargos por honorarios de anestesia que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL06', 'GLOSS', 'CL', 'CL06', FALSE, 'Dispositivos médicos'),
    ('CL0601', 'GLOSS', 'CL', 'CL06', TRUE, 'Los cargos por dispositivos médicos que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL07', 'GLOSS', 'CL', 'CL07', FALSE, 'Medicamentos y Alimentos para Propósitos Médicos Especiales - APME'),
    ('CL0701', 'GLOSS', 'CL', 'CL07', TRUE, 'Los cargos por medicamentos o APME que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL0703', 'GLOSS', 'CL', 'CL07', TRUE, 'Los cargos por medicamentos o APME que vienen relacionados en los soportes de cobro corresponden a un suministro incompleto de acuerdo a la orden o la prescripción facultativa'),
    ('CL08', 'GLOSS', 'CL', 'CL08', FALSE, 'Apoyo diagnóstico'),
    ('CL0801', 'GLOSS', 'CL', 'CL08', TRUE, 'Los cargos por apoyo diagnóstico que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL23', 'GLOSS', 'CL', 'CL23', FALSE, 'Otros procedimientos no quirúrgicos'),
    ('CL2301', 'GLOSS', 'CL', 'CL23', TRUE, 'Los cargos por otros procedimientos no quirúrgicos o actividades que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL38', 'GLOSS', 'CL', 'CL38', FALSE, 'Traslado asistencial de pacientes'),
    ('CL3801', 'GLOSS', 'CL', 'CL38', TRUE, 'Los cargos por traslado asistencial de pacientes que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL53', 'GLOSS', 'CL', 'CL53', FALSE, 'Atención de urgencia'),
    ('CL5301', 'GLOSS', 'CL', 'CL53', TRUE, 'Los servicios prestados no obedecen a una atención de urgencia de acuerdo con la definición de la normativa vigente'),
    ('CL57', 'GLOSS', 'CL', 'CL57', FALSE, 'Apoyo terapéutico'),
    ('CL5701', 'GLOSS', 'CL', 'CL57', TRUE, 'Los cargos por apoyo terapéutico que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL58', 'GLOSS', 'CL', 'CL58', FALSE, 'Procedimientos quirúrgicos e intervencionistas'),
    ('CL5801', 'GLOSS', 'CL', 'CL58', TRUE, 'Los cargos por procedimientos quirúrgicos o intervencionistas que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('CL59', 'GLOSS', 'CL', 'CL59', FALSE, 'Transporte no asistencial ambulatorio de las personas'),
    ('CL5901', 'GLOSS', 'CL', 'CL59', TRUE, 'Los cargos por transporte no asistencial ambulatorio de las personas que vienen relacionados en los soportes de cobro no son pertinentes'),
    ('SA54', 'GLOSS', 'SA', 'SA54', FALSE, 'Incumplimiento de indicadores de seguimiento'),
    ('SA5401', 'GLOSS', 'SA', 'SA54', TRUE, 'Incumplimiento o falta de evidencia del cumplimiento de los indicadores relacionados con las intervenciones obligatorias para la promoción y el mantenimiento de la salud, según lo establecido la Resolución 3280 de 2018 o la que la modifique o sustituya, según lo pactado en el acuerdo de voluntades'),
    ('SA5402', 'GLOSS', 'SA', 'SA54', TRUE, 'Incumplimiento o falta de evidencia del cumplimiento de los indicadores relacionados con las intervenciones obligatorias para la atención de población materno perinatal, según lo establecido la Resolución 3280 de 2018 o la que la modifique o sustituya, según lo pactado en el acuerdo de voluntades'),
    ('SA5403', 'GLOSS', 'SA', 'SA54', TRUE, 'Incumplimiento o falta de evidencia del cumplimiento de los indicadores relacionados con las intervenciones obligatorias para la atención de las condiciones crónicas y de alto costo, según lo establecido por la normativa vigente y lo pactado entre las partes'),
    ('SA55', 'GLOSS', 'SA', 'SA55', FALSE, 'Ajuste frente a la desviación de la nota técnica'),
    ('SA5501', 'GLOSS', 'SA', 'SA55', TRUE, 'Disminución en el número de la población inicial a atender en una modalidad de pago prospectiva'),
    ('SA5502', 'GLOSS', 'SA', 'SA55', TRUE, 'Disminución en la frecuencia observada en el uso de los servicios y tecnologías en salud frente a lo proyectado en la nota técnica'),
    ('SA56', 'GLOSS', 'SA', 'SA56', FALSE, 'Incumplimiento de indicadores de calidad, gestión y resultados'),
    ('SA5601', 'GLOSS', 'SA', 'SA56', TRUE, 'Incumplimiento de las metas, rangos y umbrales pactados de los indicadores de calidad para hacer seguimiento al acuerdo de voluntades'),
    ('SA5602', 'GLOSS', 'SA', 'SA56', TRUE, 'Incumplimiento de las metas, rangos y umbrales pactados de los indicadores de gestión para hacer seguimiento al acuerdo de voluntades'),
    ('SA5603', 'GLOSS', 'SA', 'SA56', TRUE, 'Incumplimiento de las metas, rangos y umbrales pactados de los indicadores de resultados en salud para hacer seguimiento al acuerdo de voluntades'),
    ('RE95', 'RESPONSE', 'RE', 'RE95', FALSE, 'Glosa o devolución extemporánea'),
    ('RE9501', 'RESPONSE', 'RE', 'RE95', TRUE, 'La devolución no procede por haber sido generada fuera de los términos establecidos en el artículo 6 de la Resolución 2284 de 2023'),
    ('RE9502', 'RESPONSE', 'RE', 'RE95', TRUE, 'La glosa no procede por haber sido generada fuera de los términos establecidos por la Ley configurándose la aceptación tácita de la factura de venta en salud'),
    ('RE96', 'RESPONSE', 'RE', 'RE96', FALSE, 'Glosa o devolución injustificada'),
    ('RE9601', 'RESPONSE', 'RE', 'RE96', TRUE, 'El prestador de servicios de salud o proveedor de tecnologías en salud aporta a la entidad responsable de pago la evidencia que demuestra que la devolución es injustificada al 100%'),
    ('RE9602', 'RESPONSE', 'RE', 'RE96', TRUE, 'El prestador de servicios de salud o proveedor de tecnologías en salud aporta a la entidad responsable de pago la evidencia que demuestra que la glosa es injustificada al 100%'),
    ('RE97', 'RESPONSE', 'RE', 'RE97', FALSE, 'Glosa o devolución totalmente aceptada'),
    ('RE9701', 'RESPONSE', 'RE', 'RE97', TRUE, 'El prestador de servicios de salud o proveedor de tecnologías en salud informa a la entidad responsable de pago que la devolución ha sido aceptada al 100%'),
    ('RE9702', 'RESPONSE', 'RE', 'RE97', TRUE, 'El prestador de servicios de salud o proveedor de tecnologías en salud informa a la entidad responsable de pago que la glosa ha sido aceptada al 100%'),
    ('RE98', 'RESPONSE', 'RE', 'RE98', FALSE, 'Glosa parcialmente aceptada y subsanada parcialmente'),
    ('RE9801', 'RESPONSE', 'RE', 'RE98', TRUE, 'El prestador de servicios de salud o proveedor de tecnologías en salud informa a la entidad responsable de pago que la glosa ha sido aceptada y subsanada parcialmente'),
    ('RE99', 'RESPONSE', 'RE', 'RE99', FALSE, 'Glosa no aceptada y subsanada en su totalidad'),
    ('RE9901', 'RESPONSE', 'RE', 'RE99', TRUE, 'El prestador de servicios de salud o proveedor de tecnologías en salud informa a la entidad responsable de pago que la glosa siendo justificada ha podido ser subsanada totalmente'),
    ('RE22', 'RESPONSE', 'RE', 'RE22', FALSE, 'Respuesta a devolución y glosa extemporánea'),
    ('RE2201', 'RESPONSE', 'RE', 'RE22', TRUE, 'La entidad responsable de pago informa al prestador de servicios de salud o proveedor de tecnologías en salud que la respuesta a la devolución se presenta por fuera de los términos legales, configurándose la aceptación tácita de la devolución'),
    ('RE2202', 'RESPONSE', 'RE', 'RE22', TRUE, 'La entidad responsable de pago informa al prestador de servicios de salud o proveedor de tecnologías en salud que la respuesta a la glosa se presenta por fuera de los términos legales, configurándose la aceptación tácita de la glosa');
