server:
  port: 8087

spring:
  application:
    name: clients-service
  flyway:
    location: classpath:db/migration/clients

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-service:8761/eureka/

