#!/bin/bash
set -euo pipefail

: "${POSTGRES_DB:?POSTGRES_DB is required}"

ADMISSIONS_DB_MIGRATOR_USER=$(cat "${ADMISSIONS_DB_MIGRATOR_USER_FILE:?ADMISSIONS_DB_MIGRATOR_USER_FILE is required}")
ADMISSIONS_DB_MIGRATOR_PASSWORD=$(cat "${ADMISSIONS_DB_MIGRATOR_PASSWORD_FILE:?ADMISSIONS_DB_MIGRATOR_PASSWORD_FILE is required}")
ADMISSIONS_DB_APP_USER=$(cat "${ADMISSIONS_DB_APP_USER_FILE:?ADMISSIONS_DB_APP_USER_FILE is required}")
ADMISSIONS_DB_APP_PASSWORD=$(cat "${ADMISSIONS_DB_APP_PASSWORD_FILE:?ADMISSIONS_DB_APP_PASSWORD_FILE is required}")
ADMISSIONS_DB_DEBEZIUM_USER=$(cat "${ADMISSIONS_DB_DEBEZIUM_USER_FILE:?ADMISSIONS_DB_DEBEZIUM_USER_FILE is required}")
ADMISSIONS_DB_DEBEZIUM_PASSWORD=$(cat "${ADMISSIONS_DB_DEBEZIUM_PASSWORD_FILE:?ADMISSIONS_DB_DEBEZIUM_PASSWORD_FILE is required}")

psql --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" --set ON_ERROR_STOP=on <<SQL
CREATE ROLE "${ADMISSIONS_DB_MIGRATOR_USER}" WITH LOGIN PASSWORD '${ADMISSIONS_DB_MIGRATOR_PASSWORD}';
CREATE ROLE "${ADMISSIONS_DB_APP_USER}" WITH LOGIN PASSWORD '${ADMISSIONS_DB_APP_PASSWORD}';
CREATE ROLE "${ADMISSIONS_DB_DEBEZIUM_USER}" WITH LOGIN REPLICATION PASSWORD '${ADMISSIONS_DB_DEBEZIUM_PASSWORD}';

GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${ADMISSIONS_DB_MIGRATOR_USER}", "${ADMISSIONS_DB_APP_USER}",
    "${ADMISSIONS_DB_DEBEZIUM_USER}";
GRANT CREATE ON DATABASE "${POSTGRES_DB}" TO "${ADMISSIONS_DB_MIGRATOR_USER}";

CREATE SCHEMA IF NOT EXISTS admissions_outbox AUTHORIZATION "${ADMISSIONS_DB_MIGRATOR_USER}";

GRANT USAGE ON SCHEMA admissions_outbox TO "${ADMISSIONS_DB_APP_USER}", "${ADMISSIONS_DB_DEBEZIUM_USER}";
GRANT SELECT ON ALL TABLES IN SCHEMA admissions_outbox TO "${ADMISSIONS_DB_DEBEZIUM_USER}";

ALTER DEFAULT PRIVILEGES FOR ROLE "${ADMISSIONS_DB_MIGRATOR_USER}" IN SCHEMA admissions_outbox
    GRANT SELECT, INSERT, DELETE ON TABLES TO "${ADMISSIONS_DB_APP_USER}";
ALTER DEFAULT PRIVILEGES FOR ROLE "${ADMISSIONS_DB_MIGRATOR_USER}" IN SCHEMA admissions_outbox
    GRANT SELECT ON TABLES TO "${ADMISSIONS_DB_DEBEZIUM_USER}";

ALTER DEFAULT PRIVILEGES FOR ROLE "${POSTGRES_USER}" IN SCHEMA admissions_outbox
    GRANT SELECT, INSERT, DELETE ON TABLES TO "${ADMISSIONS_DB_APP_USER}";
ALTER DEFAULT PRIVILEGES FOR ROLE "${POSTGRES_USER}" IN SCHEMA admissions_outbox
    GRANT SELECT ON TABLES TO "${ADMISSIONS_DB_DEBEZIUM_USER}";

CREATE PUBLICATION admissions_outbox_pub FOR TABLES IN SCHEMA admissions_outbox;
SQL
