#!/bin/bash
set -euo pipefail

: "${MYSQL_DATABASE:?MYSQL_DATABASE is required}"
: "${CLINICAL_DB_MIGRATOR_USER:?CLINICAL_DB_MIGRATOR_USER is required}"
: "${CLINICAL_DB_MIGRATOR_PASSWORD:?CLINICAL_DB_MIGRATOR_PASSWORD is required}"
: "${CLINICAL_DB_APP_USER:?CLINICAL_DB_APP_USER is required}"
: "${CLINICAL_DB_APP_PASSWORD:?CLINICAL_DB_APP_PASSWORD is required}"

LEDGER_SCHEMA=clinical_ledger
WORKSPACE_SCHEMA=clinical_workspace

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${CLINICAL_DB_MIGRATOR_USER}'@'%' IDENTIFIED BY '${CLINICAL_DB_MIGRATOR_PASSWORD}';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT ON \`${LEDGER_SCHEMA}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${WORKSPACE_SCHEMA}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';

CREATE USER IF NOT EXISTS '${CLINICAL_DB_APP_USER}'@'%' IDENTIFIED BY '${CLINICAL_DB_APP_PASSWORD}';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, LOCK TABLES ON \`${LEDGER_SCHEMA}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${WORKSPACE_SCHEMA}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';

FLUSH PRIVILEGES;
SQL
