#!/bin/bash
set -euo pipefail

: "${MYSQL_DATABASE:?MYSQL_DATABASE is required}"
: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"

CLINICAL_DB_MIGRATOR_USER=$(cat "${CLINICAL_DB_MIGRATOR_USER_FILE:?CLINICAL_DB_MIGRATOR_USER_FILE is required}")
CLINICAL_DB_MIGRATOR_PASSWORD=$(cat "${CLINICAL_DB_MIGRATOR_PASSWORD_FILE:?CLINICAL_DB_MIGRATOR_PASSWORD_FILE is required}")
CLINICAL_DB_APP_USER=$(cat "${CLINICAL_DB_APP_USER_FILE:?CLINICAL_DB_APP_USER_FILE is required}")
CLINICAL_DB_APP_PASSWORD=$(cat "${CLINICAL_DB_APP_PASSWORD_FILE:?CLINICAL_DB_APP_PASSWORD_FILE is required}")
CLINICAL_DB_DEBEZIUM_USER=$(cat "${CLINICAL_DB_DEBEZIUM_USER_FILE:?CLINICAL_DB_DEBEZIUM_USER_FILE is required}")
CLINICAL_DB_DEBEZIUM_PASSWORD=$(cat "${CLINICAL_DB_DEBEZIUM_PASSWORD_FILE:?CLINICAL_DB_DEBEZIUM_PASSWORD_FILE is required}")

LEDGER_SCHEMA=clinical_ledger
WORKSPACE_SCHEMA=clinical_workspace
KEYS_SCHEMA=clinical_keys
OUTBOX_SCHEMA=clinical_outbox

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${CLINICAL_DB_MIGRATOR_USER}'@'%' IDENTIFIED BY '${CLINICAL_DB_MIGRATOR_PASSWORD}';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT ON \`${LEDGER_SCHEMA}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${WORKSPACE_SCHEMA}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT ON \`${KEYS_SCHEMA}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, SELECT, INSERT, UPDATE, DELETE ON \`${OUTBOX_SCHEMA}\`.* TO '${CLINICAL_DB_MIGRATOR_USER}'@'%';

CREATE USER IF NOT EXISTS '${CLINICAL_DB_APP_USER}'@'%' IDENTIFIED BY '${CLINICAL_DB_APP_PASSWORD}';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, LOCK TABLES ON \`${LEDGER_SCHEMA}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${WORKSPACE_SCHEMA}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';
GRANT SELECT, INSERT ON \`${KEYS_SCHEMA}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, DELETE ON \`${OUTBOX_SCHEMA}\`.* TO '${CLINICAL_DB_APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${CLINICAL_DB_DEBEZIUM_USER}'@'%' IDENTIFIED BY '${CLINICAL_DB_DEBEZIUM_PASSWORD}';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${CLINICAL_DB_DEBEZIUM_USER}'@'%';
GRANT SELECT ON \`${OUTBOX_SCHEMA}\`.* TO '${CLINICAL_DB_DEBEZIUM_USER}'@'%';

FLUSH PRIVILEGES;
SQL
