server:
  port: 8085

spring:
  application:
    name: suppliers-service
  flyway:
      location: classpath:db/migration/suppliers

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-service:8761/eureka/