#!/bin/bash
set -euo pipefail

: "${MYSQL_DATABASE:?MYSQL_DATABASE is required}"
: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"

AUTH_DB_MIGRATOR_USER=$(cat "${AUTH_DB_MIGRATOR_USER_FILE:?AUTH_DB_MIGRATOR_USER_FILE is required}")
AUTH_DB_MIGRATOR_PASSWORD=$(cat "${AUTH_DB_MIGRATOR_PASSWORD_FILE:?AUTH_DB_MIGRATOR_PASSWORD_FILE is required}")
AUTH_DB_APP_USER=$(cat "${AUTH_DB_APP_USER_FILE:?AUTH_DB_APP_USER_FILE is required}")
AUTH_DB_APP_PASSWORD=$(cat "${AUTH_DB_APP_PASSWORD_FILE:?AUTH_DB_APP_PASSWORD_FILE is required}")

HISTORY_SCHEMA=auth_history
SESSIONS_SCHEMA=auth_sessions

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${AUTH_DB_MIGRATOR_USER}'@'%' IDENTIFIED BY '${AUTH_DB_MIGRATOR_PASSWORD}';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO '${AUTH_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT ON \`${HISTORY_SCHEMA}\`.* TO '${AUTH_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${SESSIONS_SCHEMA}\`.* TO '${AUTH_DB_MIGRATOR_USER}'@'%';

CREATE USER IF NOT EXISTS '${AUTH_DB_APP_USER}'@'%' IDENTIFIED BY '${AUTH_DB_APP_PASSWORD}';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.* TO '${AUTH_DB_APP_USER}'@'%';
GRANT SELECT, INSERT ON \`${HISTORY_SCHEMA}\`.* TO '${AUTH_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`${SESSIONS_SCHEMA}\`.* TO '${AUTH_DB_APP_USER}'@'%';

FLUSH PRIVILEGES;
SQL
