#!/bin/bash
set -euo pipefail

: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_DB:?POSTGRES_DB is required}"

MIGRATOR_USER=$(cat "${AI_ASSISTANT_DB_MIGRATOR_USER_FILE:?AI_ASSISTANT_DB_MIGRATOR_USER_FILE is required}")
MIGRATOR_PASSWORD=$(cat "${AI_ASSISTANT_DB_MIGRATOR_PASSWORD_FILE:?AI_ASSISTANT_DB_MIGRATOR_PASSWORD_FILE is required}")
APP_USER=$(cat "${AI_ASSISTANT_DB_APP_USER_FILE:?AI_ASSISTANT_DB_APP_USER_FILE is required}")
APP_PASSWORD=$(cat "${AI_ASSISTANT_DB_APP_PASSWORD_FILE:?AI_ASSISTANT_DB_APP_PASSWORD_FILE is required}")

SCHEMA=assistant

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -v migrator="$MIGRATOR_USER" -v migrator_password="$MIGRATOR_PASSWORD" \
  -v app="$APP_USER" -v app_password="$APP_PASSWORD" -v schema="$SCHEMA" -v db="$POSTGRES_DB" <<'SQL'
CREATE ROLE :"migrator" LOGIN PASSWORD :'migrator_password';
CREATE ROLE :"app" LOGIN PASSWORD :'app_password';

REVOKE ALL ON DATABASE :"db" FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE :"db" TO :"migrator", :"app";

CREATE SCHEMA :"schema" AUTHORIZATION :"migrator";
CREATE SCHEMA assistant_migrations AUTHORIZATION :"migrator";
GRANT USAGE ON SCHEMA :"schema" TO :"app";

ALTER DEFAULT PRIVILEGES FOR ROLE :"migrator" IN SCHEMA :"schema"
  GRANT SELECT, INSERT, UPDATE ON TABLES TO :"app";
ALTER DEFAULT PRIVILEGES FOR ROLE :"migrator" IN SCHEMA :"schema"
  GRANT USAGE, SELECT ON SEQUENCES TO :"app";
SQL
