#!/bin/bash
set -euo pipefail

: "${MYSQL_DATABASE:?MYSQL_DATABASE is required}"
: "${PATIENT_DB_MIGRATOR_USER:?PATIENT_DB_MIGRATOR_USER is required}"
: "${PATIENT_DB_MIGRATOR_PASSWORD:?PATIENT_DB_MIGRATOR_PASSWORD is required}"
: "${PATIENT_DB_APP_USER:?PATIENT_DB_APP_USER is required}"
: "${PATIENT_DB_APP_PASSWORD:?PATIENT_DB_APP_PASSWORD is required}"
: "${PATIENT_DB_DEBEZIUM_USER:?PATIENT_DB_DEBEZIUM_USER is required}"
: "${PATIENT_DB_DEBEZIUM_PASSWORD:?PATIENT_DB_DEBEZIUM_PASSWORD is required}"

OUTBOX_SCHEMA=patient_outbox

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${PATIENT_DB_MIGRATOR_USER}'@'%' IDENTIFIED BY '${PATIENT_DB_MIGRATOR_PASSWORD}';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO '${PATIENT_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, SELECT, INSERT, UPDATE, DELETE ON \`${OUTBOX_SCHEMA}\`.* TO '${PATIENT_DB_MIGRATOR_USER}'@'%';

CREATE USER IF NOT EXISTS '${PATIENT_DB_APP_USER}'@'%' IDENTIFIED BY '${PATIENT_DB_APP_PASSWORD}';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.* TO '${PATIENT_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, DELETE ON \`${OUTBOX_SCHEMA}\`.* TO '${PATIENT_DB_APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${PATIENT_DB_DEBEZIUM_USER}'@'%' IDENTIFIED BY '${PATIENT_DB_DEBEZIUM_PASSWORD}';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${PATIENT_DB_DEBEZIUM_USER}'@'%';
GRANT SELECT ON \`${OUTBOX_SCHEMA}\`.* TO '${PATIENT_DB_DEBEZIUM_USER}'@'%';

FLUSH PRIVILEGES;
SQL
