spring:
  profiles:
    active: dev

# Configuraci贸n de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    doc-expansion: none
  show-actuator: true

api:
  title: Auth Service API
  description: Microservicio para la gesti贸n de autenticaci贸n y autorizaci贸n
  version: 1.0.0
  contact:
    name: Development Team
    email: dev@example.com