server:
  port: 8086

spring:
  application:
    name: auth-service
  flyway:
    location: classpath:db/migration/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: mappings
  endpoint:
    mappings:
      enabled: true