server:
  port: 8086

spring:
  application:
    name: auth-service
  flyway:
    location: classpath:db/migration/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  # Configuraci贸n para RS256 (recomendado para producci贸n)
  algorithm: RS256

  # Configuraci贸n para HS256 (fallback)
  # algorithm: HS256
  # secret: tu-secreto-super-seguro-de-al-menos-32-caracteres-aqui

  # Tiempo de expiraci贸n en segundos (1 hora por defecto)
  expiration: ${JWT_EXPIRATION}