server:
  port: 8084

spring:
  application:
    name: ai-assistant-service
  flyway:
    location: classpath:db/migration/ai

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka