spring:
  application:
    name: ai-assistant-service
  flyway:
    location: classpath:db/migration/ai

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    doc-expansion: none
  show-actuator: true

# Información de la API
api:
  version: 1.0.0
  name: AI Assistant Service API
  description: Microservicio para la gestión de asistentes de IA
  contact:
    name: Development Team
    email: dev@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html