server:
  port: 8083

spring:
  application:
    name: admissions-service
  flyway:
    location: classpath:db/migration/admissions

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-service:8761/eureka/
