server:
  port: 8082

spring:
  application:
    name: billing-service
  flyway:
    location: classpath:db/migration/billing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
