CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS admissions;
CREATE SCHEMA IF NOT EXISTS admissions_history;
CREATE SCHEMA IF NOT EXISTS admissions_outbox;

CREATE TABLE admissions_history.revisions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    revised_at TIMESTAMP(6) NOT NULL,
    revised_by VARCHAR(36),

    CONSTRAINT pk_revisions PRIMARY KEY (id),
    CONSTRAINT chk_revisions_revised_by
        CHECK (revised_by IS NULL
            OR revised_by ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);
