CREATE TABLE admissions.service_types (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid              UUID         NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    name              VARCHAR(120) NOT NULL,
    kind              VARCHAR(20)  NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6) NOT NULL,
    updated_by        VARCHAR(36),

    CONSTRAINT pk_service_types PRIMARY KEY (id),
    CONSTRAINT uq_service_types_uuid UNIQUE (uuid),
    CONSTRAINT uq_service_types_name UNIQUE (name),
    CONSTRAINT chk_service_types_kind CHECK (kind IN ('EMERGENCY', 'INPATIENT', 'OUTPATIENT')),
    CONSTRAINT chk_service_types_status CHECK (status IN ('ACTIVE', 'RETIRED')),
    CONSTRAINT chk_service_types_retirement
        CHECK ((status = 'RETIRED' AND status_reason IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status = 'ACTIVE' AND status_reason IS NULL AND status_changed_at IS NULL))
);

CREATE TABLE admissions.locations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid              UUID         NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    name              VARCHAR(120) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6) NOT NULL,
    updated_by        VARCHAR(36),

    CONSTRAINT pk_locations PRIMARY KEY (id),
    CONSTRAINT uq_locations_uuid UNIQUE (uuid),
    CONSTRAINT uq_locations_name UNIQUE (name),
    CONSTRAINT chk_locations_status CHECK (status IN ('ACTIVE', 'RETIRED')),
    CONSTRAINT chk_locations_retirement
        CHECK ((status = 'RETIRED' AND status_reason IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status = 'ACTIVE' AND status_reason IS NULL AND status_changed_at IS NULL))
);

CREATE TABLE admissions.care_types (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid              UUID         NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    name              VARCHAR(120) NOT NULL,
    service_type_id   BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6) NOT NULL,
    updated_by        VARCHAR(36),

    CONSTRAINT pk_care_types PRIMARY KEY (id),
    CONSTRAINT uq_care_types_uuid UNIQUE (uuid),
    CONSTRAINT uq_care_types_name_per_service UNIQUE (service_type_id, name),
    CONSTRAINT fk_care_types_service_type FOREIGN KEY (service_type_id) REFERENCES admissions.service_types (id),
    CONSTRAINT chk_care_types_status CHECK (status IN ('ACTIVE', 'RETIRED')),
    CONSTRAINT chk_care_types_retirement
        CHECK ((status = 'RETIRED' AND status_reason IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status = 'ACTIVE' AND status_reason IS NULL AND status_changed_at IS NULL))
);

CREATE TABLE admissions.configuration_services (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid              UUID         NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    service_type_id   BIGINT       NOT NULL,
    location_id       BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6) NOT NULL,
    updated_by        VARCHAR(36),

    CONSTRAINT pk_configuration_services PRIMARY KEY (id),
    CONSTRAINT uq_configuration_services_uuid UNIQUE (uuid),
    CONSTRAINT uq_configuration_services_pair UNIQUE (service_type_id, location_id),
    CONSTRAINT fk_configuration_services_service_type
        FOREIGN KEY (service_type_id) REFERENCES admissions.service_types (id),
    CONSTRAINT fk_configuration_services_location
        FOREIGN KEY (location_id) REFERENCES admissions.locations (id),
    CONSTRAINT chk_configuration_services_status CHECK (status IN ('ACTIVE', 'RETIRED')),
    CONSTRAINT chk_configuration_services_retirement
        CHECK ((status = 'RETIRED' AND status_reason IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status = 'ACTIVE' AND status_reason IS NULL AND status_changed_at IS NULL))
);

CREATE TABLE admissions_history.service_types_aud (
    id                BIGINT       NOT NULL,
    rev               BIGINT       NOT NULL,
    revtype           SMALLINT,
    uuid              UUID,
    name              VARCHAR(120),
    kind              VARCHAR(20),
    status            VARCHAR(20),
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6),
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6),
    updated_by        VARCHAR(36),

    CONSTRAINT pk_service_types_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_service_types_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);

CREATE TABLE admissions_history.locations_aud (
    id                BIGINT       NOT NULL,
    rev               BIGINT       NOT NULL,
    revtype           SMALLINT,
    uuid              UUID,
    name              VARCHAR(120),
    status            VARCHAR(20),
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6),
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6),
    updated_by        VARCHAR(36),

    CONSTRAINT pk_locations_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_locations_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);

CREATE TABLE admissions_history.care_types_aud (
    id                BIGINT       NOT NULL,
    rev               BIGINT       NOT NULL,
    revtype           SMALLINT,
    uuid              UUID,
    name              VARCHAR(120),
    service_type_id   BIGINT,
    status            VARCHAR(20),
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6),
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6),
    updated_by        VARCHAR(36),

    CONSTRAINT pk_care_types_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_care_types_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);

CREATE TABLE admissions_history.configuration_services_aud (
    id                BIGINT       NOT NULL,
    rev               BIGINT       NOT NULL,
    revtype           SMALLINT,
    uuid              UUID,
    service_type_id   BIGINT,
    location_id       BIGINT,
    status            VARCHAR(20),
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6),
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6),
    updated_by        VARCHAR(36),

    CONSTRAINT pk_configuration_services_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_configuration_services_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);
