CREATE TABLE admissions.rooms (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid              UUID         NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    name              VARCHAR(60)  NOT NULL,
    location_id       BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6) NOT NULL,
    updated_by        VARCHAR(36),

    CONSTRAINT pk_rooms PRIMARY KEY (id),
    CONSTRAINT uq_rooms_uuid UNIQUE (uuid),
    CONSTRAINT uq_rooms_name_per_location UNIQUE (location_id, name),
    CONSTRAINT fk_rooms_location FOREIGN KEY (location_id) REFERENCES admissions.locations (id),
    CONSTRAINT chk_rooms_status CHECK (status IN ('ACTIVE', 'RETIRED')),
    CONSTRAINT chk_rooms_retirement
        CHECK ((status = 'RETIRED' AND status_reason IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status = 'ACTIVE' AND status_reason IS NULL AND status_changed_at IS NULL))
);

CREATE TABLE admissions.beds (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid              UUID         NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    label             VARCHAR(30)  NOT NULL,
    room_id           BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    occupant_uuid     UUID,
    created_at        TIMESTAMP(6) NOT NULL,
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6) NOT NULL,
    updated_by        VARCHAR(36),

    CONSTRAINT pk_beds PRIMARY KEY (id),
    CONSTRAINT uq_beds_uuid UNIQUE (uuid),
    CONSTRAINT uq_beds_label_per_room UNIQUE (room_id, label),
    CONSTRAINT fk_beds_room FOREIGN KEY (room_id) REFERENCES admissions.rooms (id),
    CONSTRAINT chk_beds_status
        CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', 'BLOCKED')),
    CONSTRAINT chk_beds_occupant
        CHECK ((status = 'OCCUPIED' AND occupant_uuid IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status <> 'OCCUPIED' AND occupant_uuid IS NULL)),
    CONSTRAINT chk_beds_reason
        CHECK ((status IN ('MAINTENANCE', 'BLOCKED') AND status_reason IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status NOT IN ('MAINTENANCE', 'BLOCKED') AND status_reason IS NULL)),
    CONSTRAINT chk_beds_available_is_clean
        CHECK (status <> 'AVAILABLE' OR status_changed_at IS NULL)
);

CREATE TABLE admissions.bed_stays (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid          UUID         NOT NULL,
    bed_id        BIGINT       NOT NULL,
    occupant_uuid UUID         NOT NULL,
    started_at    TIMESTAMP(6) NOT NULL,
    ended_at      TIMESTAMP(6),

    CONSTRAINT pk_bed_stays PRIMARY KEY (id),
    CONSTRAINT uq_bed_stays_uuid UNIQUE (uuid),
    CONSTRAINT fk_bed_stays_bed FOREIGN KEY (bed_id) REFERENCES admissions.beds (id),
    CONSTRAINT chk_bed_stays_period CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT excl_bed_stays_no_overlap
        EXCLUDE USING gist (bed_id WITH =, tsrange(started_at, ended_at) WITH &&)
);

CREATE INDEX idx_bed_stays_open_occupant
    ON admissions.bed_stays (occupant_uuid)
    WHERE ended_at IS NULL;

CREATE TABLE admissions_history.rooms_aud (
    id                BIGINT       NOT NULL,
    rev               BIGINT       NOT NULL,
    revtype           SMALLINT,
    uuid              UUID,
    name              VARCHAR(60),
    location_id       BIGINT,
    status            VARCHAR(20),
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6),
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6),
    updated_by        VARCHAR(36),

    CONSTRAINT pk_rooms_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_rooms_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);

CREATE TABLE admissions_history.beds_aud (
    id                BIGINT       NOT NULL,
    rev               BIGINT       NOT NULL,
    revtype           SMALLINT,
    uuid              UUID,
    label             VARCHAR(30),
    room_id           BIGINT,
    status            VARCHAR(20),
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    occupant_uuid     UUID,
    created_at        TIMESTAMP(6),
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6),
    updated_by        VARCHAR(36),

    CONSTRAINT pk_beds_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_beds_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);
