CREATE SEQUENCE admissions.admission_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE admissions.admissions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid                   UUID         NOT NULL,
    version                BIGINT       NOT NULL DEFAULT 0,
    number                 VARCHAR(20)  NOT NULL,
    patient_uuid           UUID         NOT NULL,
    cause                  VARCHAR(30)  NOT NULL,
    care_type_id           BIGINT,
    companion_full_name    VARCHAR(160),
    companion_phone_number VARCHAR(30),
    companion_relationship VARCHAR(60),
    status                 VARCHAR(20)  NOT NULL,
    status_reason          VARCHAR(500),
    status_changed_at      TIMESTAMP(6),
    created_at             TIMESTAMP(6) NOT NULL,
    created_by             VARCHAR(36),
    updated_at             TIMESTAMP(6) NOT NULL,
    updated_by             VARCHAR(36),

    CONSTRAINT pk_admissions PRIMARY KEY (id),
    CONSTRAINT uq_admissions_uuid UNIQUE (uuid),
    CONSTRAINT uq_admissions_number UNIQUE (number),
    CONSTRAINT fk_admissions_care_type FOREIGN KEY (care_type_id) REFERENCES admissions.care_types (id),
    CONSTRAINT chk_admissions_status CHECK (status IN ('REGISTERED', 'ACTIVE', 'DISCHARGED', 'CANCELLED')),
    CONSTRAINT chk_admissions_cancellation
        CHECK ((status = 'CANCELLED' AND status_reason IS NOT NULL) OR (status <> 'CANCELLED' AND status_reason IS NULL)),
    CONSTRAINT chk_admissions_moment
        CHECK ((status = 'REGISTERED' AND status_changed_at IS NULL)
            OR (status <> 'REGISTERED' AND status_changed_at IS NOT NULL)),
    CONSTRAINT chk_admissions_companion
        CHECK ((companion_full_name IS NULL AND companion_phone_number IS NULL)
            OR (companion_full_name IS NOT NULL AND companion_phone_number IS NOT NULL))
);

CREATE INDEX idx_admissions_open_patient
    ON admissions.admissions (patient_uuid)
    WHERE status IN ('REGISTERED', 'ACTIVE');

CREATE TABLE admissions.admission_phases (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid                     UUID         NOT NULL,
    kind                     VARCHAR(20)  NOT NULL,
    admission_id             BIGINT       NOT NULL,
    configuration_service_id BIGINT       NOT NULL,
    started_at               TIMESTAMP(6) NOT NULL,
    ended_at                 TIMESTAMP(6),
    opening_reason           VARCHAR(500),

    CONSTRAINT pk_admission_phases PRIMARY KEY (id),
    CONSTRAINT uq_admission_phases_uuid UNIQUE (uuid),
    CONSTRAINT fk_admission_phases_admission FOREIGN KEY (admission_id) REFERENCES admissions.admissions (id),
    CONSTRAINT fk_admission_phases_service
        FOREIGN KEY (configuration_service_id) REFERENCES admissions.configuration_services (id),
    CONSTRAINT chk_admission_phases_kind CHECK (kind IN ('EMERGENCY', 'INPATIENT', 'OUTPATIENT')),
    CONSTRAINT chk_admission_phases_period CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT excl_admission_phases_no_overlap
        EXCLUDE USING gist (admission_id WITH =, tsrange(started_at, ended_at) WITH &&)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE admissions_history.admissions_aud (
    id                     BIGINT       NOT NULL,
    rev                    BIGINT       NOT NULL,
    revtype                SMALLINT,
    uuid                   UUID,
    number                 VARCHAR(20),
    patient_uuid           UUID,
    cause                  VARCHAR(30),
    care_type_id           BIGINT,
    companion_full_name    VARCHAR(160),
    companion_phone_number VARCHAR(30),
    companion_relationship VARCHAR(60),
    status                 VARCHAR(20),
    status_reason          VARCHAR(500),
    status_changed_at      TIMESTAMP(6),
    created_at             TIMESTAMP(6),
    created_by             VARCHAR(36),
    updated_at             TIMESTAMP(6),
    updated_by             VARCHAR(36),

    CONSTRAINT pk_admissions_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_admissions_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);
