CREATE TABLE admissions.authorizations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uuid              UUID           NOT NULL,
    version           BIGINT         NOT NULL DEFAULT 0,
    admission_id      BIGINT         NOT NULL,
    number            VARCHAR(60)    NOT NULL,
    type              VARCHAR(30)    NOT NULL,
    authorized_by     VARCHAR(160),
    copayment         DECIMAL(15, 2),
    valid_from        DATE,
    valid_to          DATE,
    status            VARCHAR(20)    NOT NULL,
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6)   NOT NULL,
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6)   NOT NULL,
    updated_by        VARCHAR(36),

    CONSTRAINT pk_authorizations PRIMARY KEY (id),
    CONSTRAINT uq_authorizations_uuid UNIQUE (uuid),
    CONSTRAINT uq_authorizations_number_per_admission UNIQUE (admission_id, number),
    CONSTRAINT fk_authorizations_admission FOREIGN KEY (admission_id) REFERENCES admissions.admissions (id),
    CONSTRAINT chk_authorizations_type
        CHECK (type IN ('EMERGENCY_SERVICES', 'HOSPITALIZATION', 'AMBULATORY_SERVICES',
                        'SPECIALIZED_SERVICES', 'MEDICATIONS', 'TRANSPORT_SERVICES')),
    CONSTRAINT chk_authorizations_status CHECK (status IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT chk_authorizations_revocation
        CHECK ((status = 'REVOKED' AND status_reason IS NOT NULL AND status_changed_at IS NOT NULL)
            OR (status = 'ACTIVE' AND status_reason IS NULL AND status_changed_at IS NULL)),
    CONSTRAINT chk_authorizations_copayment CHECK (copayment IS NULL OR copayment >= 0),
    CONSTRAINT chk_authorizations_validity CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from)
);

CREATE TABLE admissions.authorization_portfolio_items (
    authorization_id    BIGINT NOT NULL,
    portfolio_item_uuid UUID   NOT NULL,

    CONSTRAINT pk_authorization_portfolio_items PRIMARY KEY (authorization_id, portfolio_item_uuid),
    CONSTRAINT fk_authorization_portfolio_items_authorization
        FOREIGN KEY (authorization_id) REFERENCES admissions.authorizations (id)
);

CREATE TABLE admissions_history.authorizations_aud (
    id                BIGINT       NOT NULL,
    rev               BIGINT       NOT NULL,
    revtype           SMALLINT,
    uuid              UUID,
    admission_id      BIGINT,
    number            VARCHAR(60),
    type              VARCHAR(30),
    authorized_by     VARCHAR(160),
    copayment         DECIMAL(15, 2),
    valid_from        DATE,
    valid_to          DATE,
    status            VARCHAR(20),
    status_reason     VARCHAR(500),
    status_changed_at TIMESTAMP(6),
    created_at        TIMESTAMP(6),
    created_by        VARCHAR(36),
    updated_at        TIMESTAMP(6),
    updated_by        VARCHAR(36),

    CONSTRAINT pk_authorizations_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_authorizations_aud_rev FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);

CREATE TABLE admissions_history.authorization_portfolio_items_aud (
    rev                 BIGINT NOT NULL,
    revtype             SMALLINT,
    authorization_id    BIGINT NOT NULL,
    portfolio_item_uuid UUID   NOT NULL,

    CONSTRAINT pk_authorization_portfolio_items_aud PRIMARY KEY (rev, authorization_id, portfolio_item_uuid),
    CONSTRAINT fk_authorization_portfolio_items_aud_rev
        FOREIGN KEY (rev) REFERENCES admissions_history.revisions (id)
);
