#!/bin/bash
set -euo pipefail

: "${MYSQL_DATABASE:?MYSQL_DATABASE is required}"
: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"

CONTRACTING_DB_MIGRATOR_USER=$(cat "${CONTRACTING_DB_MIGRATOR_USER_FILE:?CONTRACTING_DB_MIGRATOR_USER_FILE is required}")
CONTRACTING_DB_MIGRATOR_PASSWORD=$(cat "${CONTRACTING_DB_MIGRATOR_PASSWORD_FILE:?CONTRACTING_DB_MIGRATOR_PASSWORD_FILE is required}")
CONTRACTING_DB_APP_USER=$(cat "${CONTRACTING_DB_APP_USER_FILE:?CONTRACTING_DB_APP_USER_FILE is required}")
CONTRACTING_DB_APP_PASSWORD=$(cat "${CONTRACTING_DB_APP_PASSWORD_FILE:?CONTRACTING_DB_APP_PASSWORD_FILE is required}")
CONTRACTING_DB_DEBEZIUM_USER=$(cat "${CONTRACTING_DB_DEBEZIUM_USER_FILE:?CONTRACTING_DB_DEBEZIUM_USER_FILE is required}")
CONTRACTING_DB_DEBEZIUM_PASSWORD=$(cat "${CONTRACTING_DB_DEBEZIUM_PASSWORD_FILE:?CONTRACTING_DB_DEBEZIUM_PASSWORD_FILE is required}")

HISTORY_SCHEMA=contracting_history
OUTBOX_SCHEMA=contracting_outbox

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${HISTORY_SCHEMA}\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS \`${OUTBOX_SCHEMA}\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${CONTRACTING_DB_MIGRATOR_USER}'@'%' IDENTIFIED BY '${CONTRACTING_DB_MIGRATOR_PASSWORD}';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO '${CONTRACTING_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, REFERENCES, SELECT, INSERT ON \`${HISTORY_SCHEMA}\`.* TO '${CONTRACTING_DB_MIGRATOR_USER}'@'%';
GRANT CREATE, ALTER, DROP, INDEX, SELECT, INSERT, UPDATE, DELETE ON \`${OUTBOX_SCHEMA}\`.* TO '${CONTRACTING_DB_MIGRATOR_USER}'@'%';

CREATE USER IF NOT EXISTS '${CONTRACTING_DB_APP_USER}'@'%' IDENTIFIED BY '${CONTRACTING_DB_APP_PASSWORD}';
GRANT SELECT, INSERT, UPDATE ON \`${MYSQL_DATABASE}\`.* TO '${CONTRACTING_DB_APP_USER}'@'%';
GRANT SELECT, INSERT ON \`${HISTORY_SCHEMA}\`.* TO '${CONTRACTING_DB_APP_USER}'@'%';
GRANT SELECT, INSERT, DELETE ON \`${OUTBOX_SCHEMA}\`.* TO '${CONTRACTING_DB_APP_USER}'@'%';

CREATE USER IF NOT EXISTS '${CONTRACTING_DB_DEBEZIUM_USER}'@'%' IDENTIFIED BY '${CONTRACTING_DB_DEBEZIUM_PASSWORD}';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${CONTRACTING_DB_DEBEZIUM_USER}'@'%';
GRANT SELECT ON \`${OUTBOX_SCHEMA}\`.* TO '${CONTRACTING_DB_DEBEZIUM_USER}'@'%';

FLUSH PRIVILEGES;
SQL
