ALTER TABLE users
    DROP CHECK chk_users_role;

ALTER TABLE users
    ADD CONSTRAINT chk_users_role
        CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'DOCTOR', 'NURSE', 'RECEPTIONIST', 'MEDICAL_RECORDS',
                        'CONTRACTING', 'BILLING', 'ACCOUNTS_RECEIVABLE', 'HUMAN_RESOURCES'));
